export * from './NavBar'
export * from './Catalogo'
export * from './Juego'
export * from './Pregunta'
export * from './Resultado' 
export * from './PresentacionJuego'
export * from './Botones'
export * from './Card'